name: Running Code Coverage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x, 18.x]

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_DB_URI: ${{ secrets.DB_URI }}
          envkey_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          envkey_WEBHOOK_HASH: ${{ secrets.WEBHOOK_HASH }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          envkey_EXPIRES_IN: ${{ secrets.EXPIRES_IN }}
          envkey_TEMPLATE_RESET_PIN: ${{ secrets.TEMPLATE_RESET_PIN }}
          envkey_TEMPLATE_VERIFY_ACCOUNT: ${{ secrets.TEMPLATE_VERIFY_ACCOUNT }}
          envkey_TEMPLATE_TRANSFER_ID: ${{ secrets.TEMPLATE_TRANSFER_ID }}
          envkey_TEMPLATE_RECEIVED_ID: ${{ secrets.TEMPLATE_RECEIVED_ID }}
          envkey_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          envkey_FLW_SECRET_KEY: ${{ secrets.FLW_SECRET_KEY }}
          envkey_FLW_PUBLIC_KEY: ${{ secrets.FLW_PUBLIC_KEY }}
          envkey_FLW_ENCRYPTION_KEY: ${{ secrets.FLW_ENCRYPTION_KEY }}
          file_name: .env
          fail_on_empty: false

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test:cov
      - name: Get Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
